function eqOut=numCloseUp(eqIn,i,inLayer,c1,c2,c5,b2)

    eqOut=subsFor(eqIn,sprintf('psi0%d',i),...
        {sprintf('psiX%d',i),sprintf('psi1%d',i),sprintf('psiL%d',inLayer)},...
        [1/c5 -1 (2-1/c5)]);
    eqOut=subsInto(eqOut,sprintf('G1%d',i),...
        {sprintf('G0%d',i),sprintf('psiL%d',inLayer),sprintf('psiX%d',i)},...
        [1 -b2 b2]);
    eqOut=sumVars(eqOut);

    eqOut=subsFor(eqOut,sprintf('psiX%d',i),...
        {sprintf('G1%d',i),sprintf('psi1%d',i),sprintf('psiL%d',inLayer)},...
        [c2 c1 (1-c1)]);
    eqOut=sumVars(eqOut);

    eqOut=numIsolDep(eqOut);
end