function eqOut=subsIntoAvg(eqIn,i,inLayer,c1,c2)

    eqOut=subsFor(eqIn,sprintf('psiX%d',i),...
        {sprintf('G1%d',i),sprintf('psi1%d',i),sprintf('psiL%d',inLayer)},...
        [c2 c1 (1-c1)]);
    eqOut=sumVars(eqOut); %is this needed? seems unlikely...

end