function eqOut=numPassUpG(eqIn,i,inLayer,b2,c1,c2)

    eqOut=subsFor(eqIn,sprintf('G0%d',i),...
        {sprintf('psiX%d',i),sprintf('G1%d',i),sprintf('psiL%d',inLayer)},...
        [-b2 1 b2]);
    eqOut=sumVars(eqOut);
    eqOut=subsFor(eqOut,sprintf('psiX%d',i),...
        {sprintf('G1%d',i),sprintf('psi1%d',i),sprintf('psiL%d',inLayer)},...
        [c2 c1 (1-c1)]);
    eqOut=sumVars(eqOut);

end